/* eslint-disable */
// This file is autogenerated by the VFS generator. Do not edit.
// IMPORTANT: This file needs to be populated with the base64-encoded string of the NotoSansTC-Regular.ttf font file.
export const notoSansTCRegular = '';
